force-app/main/default/objects/aaprep2020_account_archive__x/aaprep2020_account_archive__x.object-meta.xml
<CustomObject>
    <description>aaprep2020$account_archive</description>
    <externalDataSource>heroku2015</externalDataSource>
    <externalName>aaprep2020$account_archive</externalName>
    <label>aaprep2020$account_archive</label>
    <pluralLabel>aaprep2020$account_archive</pluralLabel>
</CustomObject>

force-app/main/default/objects/aaprep2020_account_archive__x/fields/sfid__c.field-meta.xml
<CustomField>
    <fullName>sfid__c</fullName>
    <description>sfid</description>
    <externalDeveloperName>sfid</externalDeveloperName>
    <label>sfid</label>
    <length>18</length>
    <referenceTargetField>Warehouse__c.Phone__c</referenceTargetField>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>aaprep2020$account_archive</relationshipLabel>
    <relationshipName>aaprep2020_account_archive1</relationshipName>
    <type>IndirectLookup</type>
</CustomField>

force-app/main/default/classes/AccountListController_1.cls
public class AccountListController {
    
    @AuraEnabled
    //public static list<Account> getAccountlist(){
        
    public static list<aaprep2020_account_archive__x> getAccountlist(){    
       // return [Select id, Name,Industry,Phone from Account Order by CreatedDate desc limit 10];
        
        return [select accountsource__c  , sfid__c , accountnumber__c  from aaprep2020_account_archive__x where accountnumber__c !=null limit 10];
    }
    
    @AuraEnabled
    public static string AccountCnt(){    
        // return [Select id, Name,Industry,Phone from Account Order by CreatedDate desc limit 10];
        
        return [select accountnumber__c   from aaprep2020_account_archive__x where accountnumber__c ='123456'][0].accountnumber__c;
        //return [select name from account where name like 'AA%'][0].name;
    }
    
    @AuraEnabled
    public static void getAccountupdatedlist(Account newAcc){
        
        insert newAcc ;
    }
    
}